
// This file has been generated by the GUI designer. Do not modify.
namespace CodeCoverage
{
	public partial class PreferencesWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CodeCoverage.PreferencesWindow
			this.Name = "CodeCoverage.PreferencesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Code Coverage Preferences");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(5));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
