
// This file has been generated by the GUI designer. Do not modify.
namespace CodeCoverage.Pad
{
	public partial class InfoWidget
	{
		private global::Gtk.VBox rootVBox;

		private global::Gtk.Label titleLabel;

		private global::Gtk.Label versionLabel;

		private global::Gtk.Label label5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CodeCoverage.Pad.InfoWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CodeCoverage.Pad.InfoWidget";
			// Container child CodeCoverage.Pad.InfoWidget.Gtk.Container+ContainerChild
			this.rootVBox = new global::Gtk.VBox();
			this.rootVBox.Name = "rootVBox";
			this.rootVBox.Spacing = 6;
			this.rootVBox.BorderWidth = ((uint)(10));
			// Container child rootVBox.Gtk.Box+BoxChild
			this.titleLabel = new global::Gtk.Label();
			this.titleLabel.Name = "titleLabel";
			this.titleLabel.LabelProp = global::Mono.Unix.Catalog.GetString("VSMac-CodeCoverage Extension");
			this.titleLabel.Justify = ((global::Gtk.Justification)(2));
			this.rootVBox.Add(this.titleLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.rootVBox[this.titleLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child rootVBox.Gtk.Box+BoxChild
			this.versionLabel = new global::Gtk.Label();
			this.versionLabel.Name = "versionLabel";
			this.rootVBox.Add(this.versionLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.rootVBox[this.versionLabel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child rootVBox.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("by Arthur Demanuele");
			this.rootVBox.Add(this.label5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.rootVBox[this.label5]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.rootVBox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
