
// This file has been generated by the GUI designer. Do not modify.
namespace CodeCoverage
{
	public partial class PreferencesWidget
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label4;

		private global::Gtk.ColorButton foregroundColorButton;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label6;

		private global::Gtk.ColorButton uncoveredColorButton;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label8;

		private global::Gtk.ColorButton coveredColorButton;

		private global::Gtk.Button button1;

		private global::Gtk.Label GtkLabel1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CodeCoverage.PreferencesWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CodeCoverage.PreferencesWidget";
			// Container child CodeCoverage.PreferencesWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 100;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Foreground");
			this.hbox1.Add(this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.foregroundColorButton = new global::Gtk.ColorButton();
			this.foregroundColorButton.CanFocus = true;
			this.foregroundColorButton.Events = ((global::Gdk.EventMask)(784));
			this.foregroundColorButton.Name = "foregroundColorButton";
			this.foregroundColorButton.Title = global::Mono.Unix.Catalog.GetString("Margin Foreground Color");
			this.hbox1.Add(this.foregroundColorButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.foregroundColorButton]));
			w2.Position = 1;
			this.vbox3.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 100;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Uncovered");
			this.hbox3.Add(this.label6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.uncoveredColorButton = new global::Gtk.ColorButton();
			this.uncoveredColorButton.CanFocus = true;
			this.uncoveredColorButton.Events = ((global::Gdk.EventMask)(784));
			this.uncoveredColorButton.Name = "uncoveredColorButton";
			this.uncoveredColorButton.Title = global::Mono.Unix.Catalog.GetString("Margin Uncovered Background Color");
			this.hbox3.Add(this.uncoveredColorButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.uncoveredColorButton]));
			w5.Position = 1;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 100;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Covered");
			this.hbox5.Add(this.label8);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label8]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.coveredColorButton = new global::Gtk.ColorButton();
			this.coveredColorButton.CanFocus = true;
			this.coveredColorButton.Events = ((global::Gdk.EventMask)(784));
			this.coveredColorButton.Name = "coveredColorButton";
			this.coveredColorButton.Title = global::Mono.Unix.Catalog.GetString("Margin Covered Background Color");
			this.hbox5.Add(this.coveredColorButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.coveredColorButton]));
			w8.Position = 1;
			this.vbox3.Add(this.hbox5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Reset to Defaults");
			this.vbox3.Add(this.button1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button1]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			this.GtkAlignment.Add(this.vbox3);
			this.frame1.Add(this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Margins</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.vbox2.Add(this.frame1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;			
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.foregroundColorButton.ColorSet += new global::System.EventHandler(this.OnColorSelectionSet);
			this.uncoveredColorButton.ColorSet += new global::System.EventHandler(this.OnColorSelectionSet);
			this.coveredColorButton.ColorSet += new global::System.EventHandler(this.OnColorSelectionSet);
			this.button1.Clicked += new global::System.EventHandler(this.ResetToDefaultsClicked);
		}
	}
}
