
// This file has been generated by the GUI designer. Do not modify.
namespace CodeCoverage.Coverage
{
	public partial class CoveragePadWidget
	{
		private global::Gtk.VBox rootVBox;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label statusLabel;

		private global::Gtk.Button button4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CodeCoverage.Coverage.CoveragePadWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 150;
			this.HeightRequest = 200;
			this.Name = "CodeCoverage.Coverage.CoveragePadWidget";
			// Container child CodeCoverage.Coverage.CoveragePadWidget.Gtk.Container+ContainerChild
			this.rootVBox = new global::Gtk.VBox();
			this.rootVBox.Name = "rootVBox";
			this.rootVBox.Spacing = 6;
			// Container child rootVBox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.statusLabel = new global::Gtk.Label();
			this.statusLabel.Name = "statusLabel";
			this.hbox3.Add(this.statusLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.statusLabel]));
			w1.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find-and-replace", global::Gtk.IconSize.Menu);
			this.button4.Image = w2;
			this.hbox3.Add(this.button4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button4]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.rootVBox.Add(this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.rootVBox[this.hbox3]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.rootVBox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.button4.Clicked += new global::System.EventHandler(this.OnShowConsoleClicked);
		}
	}
}
