
// This file has been generated by the GUI designer. Do not modify.
namespace CodeCoverage
{
	public partial class ConsoleWidget
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView consoleTextView;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Button clearConsoleButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CodeCoverage.ConsoleWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CodeCoverage.ConsoleWidget";
			// Container child CodeCoverage.ConsoleWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.consoleTextView = new global::Gtk.TextView();
			this.consoleTextView.CanFocus = true;
			this.consoleTextView.Name = "consoleTextView";
			this.consoleTextView.Editable = false;
			this.consoleTextView.CursorVisible = false;
			this.consoleTextView.WrapMode = ((global::Gtk.WrapMode)(1));
			this.consoleTextView.Indent = 10;
			this.GtkScrolledWindow.Add(this.consoleTextView);
			this.hbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.clearConsoleButton = new global::Gtk.Button();
			this.clearConsoleButton.CanFocus = true;
			this.clearConsoleButton.Name = "clearConsoleButton";
			this.clearConsoleButton.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.clearConsoleButton.Image = w3;
			this.vbox1.Add(this.clearConsoleButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.clearConsoleButton]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
